create database SistemaParqueadero

use SistemaParqueadero

CREATE TABLE TBL_LOGIN
(USUARIO VARCHAR(30) NOT NULL,
 CONTRASEÑA VARCHAR(250)NOT NULL,
 ROL VARCHAR(50)) 

CREATE TABLE TBL_OPERARIO 
(ID_OPERARIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 NOMBRE_COMPLETO VARCHAR(70) NOT NULL,
 CC INT NOT NULL,
 TIPO_OPERARIO VARCHAR(50) NOT NULL,
 EDAD TINYINT NOT NULL,
 FECHA_NACIMIENTO DATE NOT NULL,
 FECHA_CONTRATACCION DATE NOT NULL,
 DIRECCION VARCHAR(25)NOT NULL )

 CREATE TABLE TBL_TURNO
  (ID_TURNO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  TIPO_TURNO VARCHAR(20) NOT NULL,
  FECHA_INICIO DATE NOT NULL,
  FECHA_FIN DATE NOT NULL)

CREATE TABLE TBL_CLIENTE
  (ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  NOMBRE_COMPLETO VARCHAR(70) NOT NULL,
  DOCUMENTO INT NOT NULL,
  TELEFONO INT NOT NULL
  )

 CREATE TABLE TBL_CLIENTE_CORREO
  (ID_CLIENTE INT IDENTITY(1,1) NOT NULL,
  CORREO VARCHAR(30)NOT NULL )

 CREATE TABLE TBL_CONVENIO
  (ID_CONVENIO INT IDENTITY(1,1) PRIMARY KEY  NOT NULL,
  TIPO_CONVENIO VARCHAR(30)NOT NULL)

 CREATE TABLE TBL_ABONO
  (ID_ABONO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  VALOR_ABONO MONEY NOT NULL)

CREATE TABLE TBL_VEHICULO
(ID_VEHICULO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 COLOR VARCHAR(30)NOT NULL,
 MARCA VARCHAR(30)NOT NULL,
 PLACA VARCHAR(30)NOT NULL,
 MODELO VARCHAR(30)NOT NULL)

CREATE TABLE TBL_SERVICIO_EXTRA
(ID_SERVICIO_EXTRA  INT IDENTITY(1,1)  PRIMARY KEY NOT NULL,
 FECHA_HORA_INICIO DATETIME NOT NULL,
 FECHA_HORA_FIN DATETIME NOT NULL,
 TIPO_SERVICIO VARCHAR(30)NOT NULL,
 OSERVASION VARCHAR(30) NOT NULL
)

CREATE TABLE TBL_SERVICIO_CLIENTE
  (ID_CLIENTE INT IDENTITY(1,1) NOT NULL,
   ID_SERVICIO_EXTRA INT NOT NULL)

CREATE TABLE TBL_RESERVA
(ID_RESERVA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 ESTADO_RESERVA VARCHAR(20),
 FECHA_LLEGADA DATETIME NOT NULL,
 HORA_LLEGADA TIME NOT NULL,
 FECHA_SALIDA DATETIME NOT NULL,
 HORA_SALIDA TIME NOT NULL,
 ID_CLIENTE INT,
 foreign key (ID_CLIENTE) references TBL_CLIENTE(ID_CLIENTE)
 ) 

CREATE TABLE TBL_PARKING
( ID_PARKING INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  HORA_INGRESO TIME NOT NULL,
  HORA_FIN TIME NOT NULL,
  UBICACION VARCHAR(30) NOT NULL)

CREATE TABLE TBL_FACTURA 
(ID_FACTURA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 FECHA_ACTUAL DATETIME NOT NULL,
 SUBTOTAL MONEY,
 IVA TINYINT,
 TOTAL MONEY)

CREATE TABLE TBL_DETALLE
(ID_DETALLE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 ITEM VARCHAR(50),
 VALOR MONEY,
 CANTIDAD TINYINT)

 ALTER TABLE TBL_TURNO ADD ID_OPERARIO INT NOT NULL
 ALTER TABLE TBL_TURNO ADD FOREIGN KEY(ID_OPERARIO) REFERENCES TBL_OPERARIO(ID_OPERARIO)

 ALTER TABLE TBL_FACTURA ADD ID_OPERARIO INT NOT NULL
 ALTER TABLE TBL_FACTURA ADD FOREIGN KEY(ID_OPERARIO) REFERENCES TBL_OPERARIO(ID_OPERARIO)

 ALTER TABLE TBL_FACTURA ADD ID_DETALLE INT NOT NULL
 ALTER TABLE TBL_FACTURA ADD FOREIGN KEY(ID_DETALLE) REFERENCES TBL_DETALLE(ID_DETALLE)

 ALTER TABLE TBL_PARKING ADD ID_OPERARIO INT NOT NULL
 ALTER TABLE TBL_PARKING ADD FOREIGN KEY(ID_OPERARIO) REFERENCES TBL_OPERARIO(ID_OPERARIO)

 ALTER TABLE TBL_SERVICIO_EXTRA ADD ID_OPERARIO INT NOT NULL
 ALTER TABLE TBL_SERVICIO_EXTRA ADD FOREIGN KEY(ID_OPERARIO) REFERENCES TBL_OPERARIO(ID_OPERARIO)

 ALTER TABLE TBL_SERVICIO_CLIENTE ADD FOREIGN KEY(ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE)

 ALTER TABLE TBL_SERVICIO_CLIENTE ADD FOREIGN KEY(ID_SERVICIO_EXTRA) REFERENCES TBL_SERVICIO_EXTRA(ID_SERVICIO_EXTRA)

 ALTER TABLE TBL_CONVENIO ADD ID_CLIENTE INT NOT NULL
 ALTER TABLE TBL_CONVENIO ADD FOREIGN KEY(ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE)

 ALTER TABLE TBL_RESERVA ADD ID_CLIENTE INT NOT NULL
 ALTER TABLE TBL_RESERVA ADD FOREIGN KEY(ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE)

 ALTER TABLE TBL_VEHICULO ADD ID_CLIENTE INT NOT NULL
 ALTER TABLE TBL_VEHICULO ADD FOREIGN KEY(ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE)

 ALTER TABLE TBL_PARKING ADD ID_VEHICULO INT NOT NULL
 ALTER TABLE TBL_PARKING ADD FOREIGN KEY(ID_VEHICULO) REFERENCES TBL_VEHICULO(ID_VEHICULO)

 ALTER TABLE TBL_ABONO ADD ID_CLIENTE INT NOT NULL
 ALTER TABLE TBL_ABONO ADD FOREIGN KEY(ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE)

 ALTER TABLE TBL_CLIENTE_CORREO ADD FOREIGN KEY(ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE)


						 select * from TBL_CLIENTE
						 select * from TBL_RESERVA
						 select * from TBL_VEHICULO

						 SELECT        dbo.TBL_VEHICULO.ID_VEHICULO, dbo.TBL_VEHICULO.COLOR, dbo.TBL_VEHICULO.MARCA, dbo.TBL_VEHICULO.PLACA, dbo.TBL_VEHICULO.MODELO, dbo.TBL_VEHICULO.ID_CLIENTE, 
                         dbo.TBL_RESERVA.FECHA_LLEGADA
FROM            dbo.TBL_CLIENTE INNER JOIN
                         dbo.TBL_RESERVA ON dbo.TBL_CLIENTE.ID_CLIENTE = dbo.TBL_RESERVA.ID_CLIENTE INNER JOIN
                         dbo.TBL_VEHICULO ON dbo.TBL_CLIENTE.ID_CLIENTE = dbo.TBL_VEHICULO.ID_CLIENTE
